fix: dockerfile

diff --git a/Dockerfile.main b/Dockerfile.main
--- a/Dockerfile.main
+++ b/Dockerfile.main
@@ -1,5 +1,7 @@
 # deps
 FROM node:16-alpine AS deps
+ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
+  CHROME_BIN=/usr/bin/chromium-browser
 RUN apk add --no-cache \
   libc6-compat \
   chromium \
@@ -10,24 +12,32 @@ RUN apk add --no-cache \
   ttf-freefont \
   nodejs \
   yarn
-WORKDIR /app
-
-COPY package.json package-lock.json* ./
-RUN \
-  [ -f package-lock.json ] && npm ci || \
-  (echo "Lockfile not found." && exit 1)
-
-ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
-  PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
-
-RUN npm install puppeteer --unsafe-perm=true --allow-root
-
+RUN npm install -g puppeteer --unsafe-perm=true --allow-root
 RUN addgroup -S pptruser && adduser -S -G pptruser pptruser \
   && mkdir -p /home/pptruser/Downloads /app \
   && chown -R pptruser:pptruser /home/pptruser \
   && chown -R pptruser:pptruser /app
 
 USER pptruser
+WORKDIR /app
+
+COPY package.json package-lock.json* ./
+RUN \
+  # [ -f package-lock.json ] && npm ci || \
+  [ -f package-lock.json ] && npm install || \
+  (echo "Lockfile not found." && exit 1)
+
+# ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
+#   PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
+
+# RUN npm install -g puppeteer --unsafe-perm=true --allow-root
+
+# RUN addgroup -S pptruser && adduser -S -G pptruser pptruser \
+#   && mkdir -p /home/pptruser/Downloads /app \
+#   && chown -R pptruser:pptruser /home/pptruser \
+#   && chown -R pptruser:pptruser /app
+
+# USER pptruser
 
 # builder
 FROM node:16-alpine AS builder
